version: '3'

networks:
  sahdo-network:
    driver: bridge
    ipam:
      driver: default

services:
  sahdo-nginx:
    container_name: sahdo-nginx
    image: nginx
    ports:
      - '8000:80'
    links:
      - sahdo-php
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/access.log:/var/log/nginx/access.log
      - ./docker/logs/error.log:/var/log/nginx/error.log
    networks:
      - sahdo-network

  sahdo-php:
    container_name: sahdo-php
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: sahdo-php
    image: sahdo/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
    networks:
      - sahdo-network

  sahdo-mysql:
    container_name: sahdo-mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST="%""
      - MYSQL_DATABASE=task_manager
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    networks:
      - sahdo-network
